apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-gray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3-gray
  template:
    metadata:
      labels:
        app: service3-gray
    spec:
      containers:
        - name: springcloud-service3
          image: koderover.tencentcloudcr.com/test/springcloud-service3:gray
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
